name: CI Databricks Sync

on:
  push:
    branches:
      - dev
      - test
      - main
    paths:
      - 'src/**'

jobs:
  sync-databricks:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # Dynamically selects the environment based on branch name
    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      # Download the Databricks CLI. See https://github.com/databricks/setup-cli
      - uses: databricks/setup-cli@main

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # DEBUG
      - name: Print GitHub branch name
        run: |
          echo "This workflow was triggered by branch: ${{ steps.extract_branch.outputs.branch }}"

      - name: Pull latest changes into Databricks Repo
        run: |
          databricks repos update ${{ secrets.DATABRICKS_REPO_PATH }} --branch ${{ steps.extract_branch.outputs.branch }}