name: Sync Databricks Repo Based on Branch

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  sync-databricks:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # Dynamically selects the environment based on branch name

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI
        run: |
          databricks configure --host ${{ secrets.DATABRICKS_HOST }} --token ${{ secrets.DATABRICKS_TOKEN }}

      - name: Pull latest changes into Databricks Repo
        run: |
          databricks repos update --path ${{ secrets.DATABRICKS_REPO_PATH }} --branch $GITHUB_REF_NAME