name: CI Databricks Sync

on:
  push:
    branches:
      - dev
      - test
      - main

jobs:
  sync-databricks:
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}  # Dynamically selects the environment based on branch name

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Set Databricks Environment Variables
        run: |
          export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}
          export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN }}

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      # DEBUG
      - name: Print GitHub branch name
        run: |
          echo "This workflow was triggered by branch: ${{ steps.extract_branch.outputs.branch }}"

      - name: Pull latest changes into Databricks Repo
        run: |
          databricks repos update --path ${{ secrets.DATABRICKS_REPO_PATH }} --branch "${{ steps.extract_branch.outputs.branch }}"